//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Talegen.Common.Core.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Talegen.Common.Core.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must be greater than 0..
        /// </summary>
        public static string ArgumentMustBeGreaterThanZeroErrorFormat {
            get {
                return ResourceManager.GetString("ArgumentMustBeGreaterThanZeroErrorFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authentication key must be {0} bits in length..
        /// </summary>
        public static string CryptoAuthKeyLengthErrorText {
            get {
                return ResourceManager.GetString("CryptoAuthKeyLengthErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cryptography key must be {0} bits in length..
        /// </summary>
        public static string CryptoKeyLengthErrorText {
            get {
                return ResourceManager.GetString("CryptoKeyLengthErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The content specified was not recognized as valid encrypted data..
        /// </summary>
        public static string CryptoMustSpecifyCryptoTextToDecryptErrorText {
            get {
                return ResourceManager.GetString("CryptoMustSpecifyCryptoTextToDecryptErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No data specified for encryption..
        /// </summary>
        public static string CryptoMustSpecifyTextToEncryptErrorText {
            get {
                return ResourceManager.GetString("CryptoMustSpecifyTextToEncryptErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file specified was not found..
        /// </summary>
        public static string DeserializeFileNotFoundErrorText {
            get {
                return ResourceManager.GetString("DeserializeFileNotFoundErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid argument. Argument must be an enumeration..
        /// </summary>
        public static string InvalidArgumentMustBeEnumerationText {
            get {
                return ResourceManager.GetString("InvalidArgumentMustBeEnumerationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A valid file path must be specified..
        /// </summary>
        public static string InvalidFileArgumentErrorText {
            get {
                return ResourceManager.GetString("InvalidFileArgumentErrorText", resourceCulture);
            }
        }
    }
}
